config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }

  root 'home#index'

  resources :users do
    resources :posts do
      resources :comments
    end
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	has_ancestry

	validates :user_id, presence: true
	validates :post_id, presence: true
	validates :content, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :user_id, presence: true
	validates :description,  :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts,    dependent: :destroy
  has_many :comments, dependent: :destroy
  #has_many :comments
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#", :small => "50x50#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #attr_accessor :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar, :password_confirmation) }
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  #def index
  #  @comments = Comment.all
  #end

  # GET /comments/1
  # GET /comments/1.json
  def show
    
  end

  # GET /comments/new
  def new
    #@comment = Comment.new
    @comment = Comment.new(:parent_id => params[:parent_id])
    @post_id = params[:post_id]
  #/users/:user_id/posts/:post_id/comments/new
  end

  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to user_post_path(@comment.post.user_id, @comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js   { }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to user_post_path(@comment.post.user_id, @comment.post_id), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render layout: false }
    end
 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      #@comment = Comment.find(params[:id])
      @comment = current_user.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id, :id, :ancestry)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new]
  
  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.all
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    #@post = current_user.posts.find(params[:id])
    #@comment = Comment.new(:parent_id => params[:parent_id])
    @comment = Comment.new
    @post_id = params[:id]
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new

  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        PostMailer.post_new_email(@post).deliver
        format.html { redirect_to user_path(current_user), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to user_path(current_user), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :user_id, :id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
                             @user.update_with_password(user_params)
                           else
                             # remove the virtual current_password attribute update_without_password
                             # doesn't know how to ignore it
                             params[:user].delete(:current_password)
                             @user.update_without_password(user_params)
                           end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end

  private

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email] ||
        params[:user][:password].present? ||
        user.name != params[:user][:name]
  end

  # Using a private method to encapsulate the permissible parameters is
  # just a good pattern since you'll be able to reuse the same permit
  # list between create and update. Also, you can specialize this method
  # with per-user checking of permissible attributes.
  def user_params
    params.require(:user).permit(:avatar, :email, :current_password, :password, :password_confirmation, :name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  # GET /users
  # GET /users.json
  def index
    #@users = User.all
    @users = User.paginate(page: params[:page], per_page: 10) 
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #@user = current_user
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Blog Web Application"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/blog_web_application_helper.rb
module BlogWebApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
user: #{comment.user.name}
%br
%img{ alt: "...", :src => comment.user.avatar.url(:small) }
%br
created: #{comment.created_at.strftime("%B %d, %Y")}
%br
= comment.content
%br
= link_to "Reply", new_user_post_comment_path(:post_id => comment.post_id, :parent_id => comment)
= link_to "Destroy", [comment.post.user, comment.post, comment], :confirm => "Are you sure?", :method => :delete, remote: true, :class => "delete" if comment.user_id == current_user.id || comment.post.user_id == current_user.id

app/views/comments/_form.html.haml
.col-md-8
  = simple_form_for(@comment,:url => {:action => "index"}, html: { class: 'form-horizontal' }) do |f|
    = f.error_notification

    .form-inputs
    = f.input :content, label: false, :as => :text, :input_html => { :rows => 7 , :style => 'width: 100%'}
    = f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
    = f.input :post_id, :as => :hidden, :input_html => { :value => @post_id }
    -#= f.input :ancestry, :as => :hidden, :input_html => {:value => params[:parent_id]}
    .form-actions
    = f.button :submit
    = link_to 'Back', user_path(current_user), {:class=>"btn btn-default"}

app/views/comments/create.js.erb
$("#comments").append("<li><%= escape_javascript(render @comment, locals: {comment: @comment}) %></li>");

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th
      %th
      %th
      
  %tbody
    - @comments.each do |comment|
      %tr
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment
- if @comment.errors.any?
  .alert.alert-danger#error_explanation
    -#%h3= "#{pluralize(object.errors.count, "ошибки")} при заполнении формы:"
    %h3= "Ошибки при заполнении формы:"
    %ul
      - @comment.errors.messages.each do |amsg|
        - amsg[1].each do |msg|
          %li= msg


= render 'form'

app/views/comments/show.html.haml
%h3
= @comment.content


= link_to 'Comment', new_user_post_comment_path(current_user, @post), {:class=>"btn btn-default"}

app/views/home/index.html.haml
.center.hero-unit
  %h1 Blog Web Application
  %p Если Вы хотите оставить свое сообщение, то должны #{link_to "зарегистрироваться",  new_user_registration_path} или #{link_to "войти", new_user_session_path} 
  %p 

app/views/layouts/application.html.haml
!!! Strict
%html
  %head
    %title= full_title(yield(:title))
    %meta{:name => "description", :content => h(yield(:meta_desc) || "")}
    %meta{:name => "keywords", :content => h(yield(:meta_keywords) || "")}

    = csrf_meta_tag
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag :application

    = yield(:head)


  %body
    #wrap
      = render 'shared/top'

      .container.container-main
        = render 'shared/flash'

        = yield(:page_header)

        = content_for?(:content) ? yield(:content) : yield

    = render 'shared/footer'

app/views/posts/_comment_form.html.haml
.col-md-8
  = simple_form_for([@post.user, @post, @comment], html: { class: 'form-horizontal' }, remote: true) do |f|
    = f.error_notification

    
    = f.input :content, label: false, :as => :text, :input_html => { :rows => 7 , :style => 'width: 100%'}
    = f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
    = f.input :post_id, :as => :hidden, :input_html => { :value => @post_id }
    -#= f.input :ancestry, :as => :hidden, :input_html => {:value => params[:parent_id]}
    
    = f.button :submit
    = link_to 'Back', user_path(current_user), {:class=>"btn btn-default"}

app/views/posts/_comments.html.haml
-comments.each do |comment|
  %li{:id => comment.id}
    = render comment

app/views/posts/_form.html.haml
.col-md-8
  -#= horizontal_simple_form_for @user do |f|
  = simple_form_for(@post,:url => {:action => "index"}, html: { class: 'form-horizontal' }) do |f|
    = f.error_notification
    .form-inputs
    = f.input :description, label: false, :as => :text, :input_html => { :rows => 7 , :style => 'width: 100%'}
    = f.input :user_id, as: :hidden

    .form-actions
    = f.button :submit
    = link_to 'Back', user_path(current_user), {:class=>"btn btn-default"}

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts


= will_paginate @posts
%ul      
  - @posts.each do |post|
    %br
    = link_to post.description, user_post_path(current_user, post)
    = post.created_at
    = link_to post.user.email, user_path(post)
= will_paginate @posts

app/views/posts/new.html.haml
%h1 My new post create

= render 'form'

app/views/posts/show.html.haml
%h5
  user: #{@post.user.name}
  %br
  %img{alt: "...", :src => @post.user.avatar.url(:thumb)}
  %br
  created: #{@post.created_at.strftime("%B %d, %Y")}
  %br
=@post.description
%br
%br 

%ul{:id => "comments"}
  = render 'comments', comments: @post.comments
= render 'comment_form'
-#= link_to 'Add comment', new_user_post_comment_path(@post.user_id, @post), {:class=>"btn btn-default"}
-#= link_to 'Back', user_path(current_user), {:class=>"btn btn-default"}
:javascript
  $("ul#comments").on( "ajax:success", "li a.delete", function() {
    $(this).closest('li').hide();
  });

app/views/shared/_flash.html.haml
- flash.each do |name, msg|
  %div.alert.alert-info
    = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)

app/views/shared/_footer.html.haml
#footer
  .container
    %p.text-muted.credit
      ALEX D.com
      @ #{Time.now.year}.

app/views/shared/_form_errors.html.haml
- if object.errors.any?
  #error_explanation
    -#  %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_top.html.haml
/ Fixed navbar
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Blog Web Application", root_path, :class => 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to 'Create post', new_user_post_path(current_user)
          %li= link_to 'Find users', users_path
          %li= link_to 'My page', user_path(current_user)
          %li
            %a{:href => edit_user_registration_path}
              = fa_icon "cogs"
              Edit profile
          
          %li= link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Find users', users_path
          %li= link_to "Sign up", new_user_registration_path
          %li= link_to "Sign in", new_user_session_path

    / /.nav-collapse

app/views/users/_user.html.haml
-if current_user.id == @user.id
  %h1
    My Page
-else
  %h1
    #{@user.name}'s page
.row
  .col-sm-12.col-md-5.col-md-offset-3
    .thumbnail
      %img{alt: "...", :src => @user.avatar.url(:thumb)}/
      .caption.center
        %h3 #{@user.name}
        = fa_icon "envelope"
        = @user.email
        %hr
%ul
  = link_to 'Create post', new_user_post_path(@user), {:class=>"btn btn-default"} if current_user.id == @user.id
  -if @user.posts.any?
    %h4 Posts:
    -@posts.each do |post|

      %li
        = link_to post.description, user_post_path(@user, post)
      %br
        Posted #{time_ago_in_words(post.created_at)} ago.
      %br
        = link_to 'Destroy', user_post_path(@user, post), :method => :delete, :data => { :confirm => 'Are you sure?' }, remote: true if current_user.id == @user.id
      
  -else
    %h3 no posts

app/views/users/index.html.haml
%h1 All users

= will_paginate @users

%ul
  -@users.each do |user|
    %li= link_to user.email, user
      
= will_paginate @users
      

app/views/users/show.html.haml
= render @user


= will_paginate @posts